package org.pitestidea.toolwindow;

import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.module.Module;
import com.intellij.openapi.ui.MessageDialogBuilder;
import com.intellij.openapi.util.IconLoader;
import com.intellij.openapi.vfs.InvalidVirtualFileAccessException;
import com.intellij.openapi.vfs.LocalFileSystem;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.ui.JBColor;
import com.intellij.ui.components.JBScrollPane;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.pitestidea.actions.ExecutionUtils;
import org.pitestidea.configuration.IdeaDiscovery;
import org.pitestidea.model.*;
import org.pitestidea.render.CoverageGutterRenderer;
import org.pitestidea.render.FileOpenCloseListener;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Consumer;

/**
 * Manages execution results tool window. Consists of several panes with different levels of interactivity.
 */
public class MutationControlPanel {
    private static final Logger LOGGER = Logger.getInstance(MutationControlPanel.class);

    private final HistoryList historyList = new HistoryList();
    private final StretchPane stretchPane = new StretchPane(this::handleStretchPaneChanged);

    private final JScrollPane rightScrollPane = new JBScrollPane();
    private final ClickTree tree = new ClickTree();
    private Consumer<DisplayChoices> optionsChangeFn = null;
    private EnumRadio<Viewing.PackageChoice> packageSelector;
    private EnumRadio<Sorting.By> sortSelector;
    private EnumRadio<Sorting.Direction> dirSelector;
    private JButton clearAllButton;
    private boolean isGutterIconsEnabled = true;
    private int headerHeight;  // For aligning headers across different panes
    private final AtomicInteger activeRuns = new AtomicInteger(0);

    public MutationControlPanel() {
        stretchPane.setLeft(createScoresPanel());  // Run 1st to set headerHeight;
        stretchPane.setRight(createConsolePane());
        stretchPane.setState(StretchPane.PaneState.SCORES);
    }

    private JPanel createConsolePane() {
        JPanel fullPanel = new JPanel(new BorderLayout());

        JPanel header = new JPanel(new BorderLayout());
        JLabel label = stretchPane.getConsoleButton();
        header.add(label, BorderLayout.WEST);
        // Align header heights with small fudge factor
        header.setPreferredSize(new Dimension(20, headerHeight+4));
        fullPanel.add(header, BorderLayout.NORTH);
        fullPanel.add(rightScrollPane, BorderLayout.CENTER);

        return fullPanel;
    }

    private JSplitPane scoresSplitPane;
    private void handleStretchPaneChanged(StretchPane.PaneState s) {
        if (s == StretchPane.PaneState.SCORES) {
            // setting divider only works properly if visible
            scoresSplitPane.getLeftComponent().setVisible(true);
            setDefaultScoresSplit();
        } else {
            scoresSplitPane.getLeftComponent().setVisible(false);
        }
    }

    private JComponent createScoresPanel() {
        scoresSplitPane = new JSplitPane();

        scoresSplitPane.setLeftComponent(createHistoryPanel());

        JPanel treePanel = new JPanel(new BorderLayout());
        treePanel.add(createScoresHeaderPanel(), BorderLayout.NORTH);
        treePanel.add(tree, BorderLayout.CENTER);
        scoresSplitPane.setRightComponent(treePanel);
        setDefaultScoresSplit();

        return new JBScrollPane(scoresSplitPane);
    }

    public void setDefaultScoresSplit() {
        double split = 0.3;
        scoresSplitPane.setDividerLocation(split);
        scoresSplitPane.setResizeWeight(split);
    }

    public void onFirstActivation(CachedRun cachedRun) {
        reloadScores(cachedRun);
        // Quirk: the values in this method do not take effect until the split is visible
        setDefaultScoresSplit();
    }

    private JPanel createHistoryPanel() {
        JPanel panel = new JPanel(new BorderLayout());
        panel.add(createHistoryHeaderPanel(), BorderLayout.NORTH);
        panel.add(historyList.getComponent(), BorderLayout.CENTER);
        return panel;
    }

    private JPanel createHistoryHeaderPanel() {
        JPanel header = new JPanel(new FlowLayout(FlowLayout.LEFT));
        JPanel options = new JPanel();
        options.setBorder(BorderFactory.createLineBorder(JBColor.BLACK));
        clearAllButton = createClearAllButton();
        options.add(clearAllButton);
        header.add(options);
        return header;
    }

    private @NotNull JButton createClearAllButton() {
        JButton button = new JButton("Clear All");
        button.setToolTipText("Delete all PIT reports for this project that were generated by this plugin. Does <i>not</i> delete reports generated by other plugins or by the PIT CLI.");
        Project project = IdeaDiscovery.getActiveProject();
        button.addActionListener(e -> {
            ApplicationManager.getApplication().invokeLater(() -> {
                if (MessageDialogBuilder.okCancel("Really delete all PIT reports for this project?", "Cannot be undone")
                        .yesText("Confirm")
                        .noText("Cancel")
                        .ask(project)) {
                    PitRepo.deleteHistory(project);
                    clearHistory();
                    PitRepo.reloadReports(project);
                }
            });
        });
        button.setEnabled(false);  // enabled on report load
        return button;
    }

    private JPanel createScoresHeaderPanel() {
        JPanel header = new JPanel(new BorderLayout());
        header.setLayout(new BoxLayout(header, BoxLayout.X_AXIS)); // Horizontal layout
        header.add(createPackagePanel());
        header.add(createSortPanel());
        header.add(createDirPanel());

        header.add(Box.createHorizontalGlue());
        header.add(createRemoveButton());
        header.add(Box.createHorizontalGlue());
        header.add(stretchPane.getScoresButton());
        headerHeight = header.getPreferredSize().height;
        return header;
    }

    private JComponent createRemoveButton() {
        Project project = IdeaDiscovery.getActiveProject();
        JCheckBox checkBox = new JCheckBox("Show PIT icons");
        checkBox.setHorizontalAlignment(SwingConstants.CENTER);
        checkBox.setSelected(isGutterIconsEnabled);
        checkBox.addActionListener(e -> {
            isGutterIconsEnabled = checkBox.isSelected();
            if (isGutterIconsEnabled) {
                FileOpenCloseListener.replayOpenFiles(project);
            } else {
                CoverageGutterRenderer.removeGutterIcons(project);
            }
        });
        return checkBox;
    }

    private JPanel createPackagePanel() {
        packageSelector = new EnumRadio<>(Viewing.PackageChoice.values(),"Filter",
                Viewing.PackageChoice::getDisplayName,
                type -> callOptionsChangeFn());
        packageSelector.setSelected(Viewing.PackageChoice.PACKAGE); // Default value
        return packageSelector.getPanel();
    }

    private JPanel createSortPanel() {
        sortSelector = new EnumRadio<>(Sorting.By.values(),"Sort",
                Sorting.By::getDisplayName,
                type -> callOptionsChangeFn());
        sortSelector.setSelected(Sorting.By.PROJECT); // Default value
        return sortSelector.getPanel();
    }

    private JPanel createDirPanel() {
        dirSelector = new EnumRadio<>(Sorting.Direction.values(),"Sort Direction",
                Sorting.Direction::getDisplayName,
                type -> callOptionsChangeFn());
        dirSelector.setSelected(Sorting.Direction.ASC); // Default value

        return dirSelector.getPanel();
    }

    public DisplayChoices getDisplayChoices() {
        return new DisplayChoices(getPackageSelection(), sortSelector.getSelected(), dirSelector.getSelected());
    }

    public void setOptionsChangeFn(Consumer<DisplayChoices> optionsChangeFn) {
        this.optionsChangeFn = optionsChangeFn;
    }

    private void callOptionsChangeFn() {
        optionsChangeFn.accept(getDisplayChoices());
    }

    public Viewing.PackageChoice getPackageSelection() {
        return packageSelector.getSelected();
    }

    public void setPackageSelection(Viewing.PackageChoice packageChoice) {
        packageSelector.setSelected(packageChoice);
    }

    public void setSortSelection(Sorting.By sortChoice) {
        sortSelector.setSelected(sortChoice);
    }

    public void setDirSelection(Sorting.Direction dirChoice) {
        dirSelector.setSelected(dirChoice);
    }

    public JComponent getContentPanel() {
        return stretchPane.getComponent();
    }

    public void clearScores(Project project) {
        clearScores(PitRepo.getCurrent(project));
    }

    public void clearScores(CachedRun cachedRun) {
        tree.clearExistingRows();
        syncScoresMsg(cachedRun);
        tree.refresh();
    }

    public void refresh() {
        tree.refresh();
    }

    public Level getLevel() {
        return new Level(tree.getRootTreeLevel());
    }

    /**
     * Sets the body of the right panel. This is provided because the console component is
     * generated externally on PIT execution.
     *
     * @param component to set as right component (inside an already existing scroll pane)
     */
    public void setRightPaneContent(JComponent component) {
        rightScrollPane.setViewportView(component);
    }

    public void setFullConsole() {
        stretchPane.setFullConsole();
    }

    public void setFullScores() {
        stretchPane.setFullScores();
    }

    public void clearHistory() {
        historyList.clear();
    }

    public void reloadReports(Project project) {
        System.out.println("Reloading reports for " + project.getName());
        CachedRun current = reloadHistory(project);
        clearScores(current);
        if (current != null) {
            reloadScores(current);
        }
    }

    public CachedRun reloadHistory(Project project) {
        System.out.println("Reloading history for " + project.getName());
        clearHistory();
        class CrossHistory {
            boolean anyDeletable = false;
            CachedRun current = null;
            int maxStartWidth = 0;
            int maxDurationWidth = 0;
        }
        final CrossHistory crossHistory = new CrossHistory();

        PitRepo.apply(project, (c,current)->{
            ExecutionRecord record = c.getExecutionRecord();
            if (record.isRunnable()) {
                crossHistory.anyDeletable = true;
            }
            if (current) {
                crossHistory.current = c;
            }
            crossHistory.maxStartWidth = Math.max(crossHistory.maxStartWidth, record.getFormattedStart().length());
            crossHistory.maxDurationWidth = Math.max(crossHistory.maxDurationWidth, record.getFormattedDuration().length());
        });
        PitRepo.apply(project, (c,current)->{
            addHistory(c, new HistoryList.Sizing(crossHistory.maxStartWidth, crossHistory.maxDurationWidth));
        });
        clearAllButton.setEnabled(crossHistory.anyDeletable);
        if (!crossHistory.anyDeletable) {
            reloadScoresMsg(project, "No current history. Initiate PIT execution from a drop-down menu.");
        } else if (crossHistory.current==null) {
            reloadScoresMsg(project, "Choose a report from the history list to the left.");
        }
        historyList.getComponent().updateUI();
        return crossHistory.current;
    }

    private void reloadScoresMsg(Project project, String msg) {
        System.out.println("Reloading scoresMsg for " + project.getName() + ": " + msg);
        CoverageGutterRenderer.removeGutterIcons(project);
        clearScores(project);
        tree.resetToRootMessage(msg);
    }

    public void reloadScores(CachedRun cachedRun) {
        if (cachedRun.isCurrent()) {
            System.out.println("Reloading scores for " + cachedRun.getExecutionRecord().getReportName());
            Project project = cachedRun.getProject();
            CoverageGutterRenderer.removeGutterIcons(project);
            clearScores(cachedRun);
            PitToolWindowFactory.addAll(project,this,cachedRun.getRecorder());
            // previous addAll will have update default scores message, make sure it's set properly
            // here for all the non-completion cases
            syncScoresMsg(cachedRun);
            if (isGutterIconsEnabled && cachedRun.getRunState()==RunState.COMPLETED) {
                FileOpenCloseListener.replayOpenFiles(project);
            }
        }
    }

    private void syncScoresMsg(@Nullable CachedRun cachedRun) {
        if (cachedRun != null && cachedRun.isCurrent()) {
            String msg = "...";
            RunState runState = cachedRun.getRunState();
            switch (runState) {
                case COMPLETED:
                    return;
                case RUNNING:
                    msg = "PIT execution is still running. Please wait.";
                    break;
                case FAILED:
                    msg = "PIT execution failed. See console for details.";
                    break;
                case CANCELLED:
                    msg = "Run was cancelled. Rerun in order to see report.";
            }
            tree.resetToRootMessage(msg);
        }
    }



    private static final Icon runIcon = IconLoader.getIcon("/icons/run.svg", MutationControlPanel.class);
    private static final Icon killIcon = IconLoader.getIcon("/icons/killProcess.svg", MutationControlPanel.class);
    private static final Icon deleteIcon = IconLoader.getIcon("/icons/delete.svg", MutationControlPanel.class);
    private static final Icon syncIcon = IconLoader.getIcon("/icons/settingSync.svg", MutationControlPanel.class);


    /**
     * Adds a row in the history pane representing the state of the supplied CachedRun.
     * Does not check for duplicates.
     *
     * @param cachedRun to read from
     */
    public void addHistory(CachedRun cachedRun, HistoryList.Sizing sizing) {
        ExecutionRecord record = cachedRun.getExecutionRecord();
        boolean isCurrent = cachedRun.isCurrent();
        RunState runState = cachedRun.getRunState();
        boolean valid = runState.isValid();
        JPanel row = historyList.addRow(record, isCurrent, valid, sizing, cachedRun::activate);
        TransitionButton button = new TransitionButton();
        boolean readyToCancel = runState == RunState.RUNNING;

        if (record.isRunnable()) {
            ExecutionUtils.dumpThreads("MutationControlPanel.addHistory");
            TransitionButton.State running = button.addState("Run", runIcon, "Rerun this report", !readyToCancel, () -> run(cachedRun, button));
            button.addState("Cancel", killIcon, "Cancel this report execution", readyToCancel, () -> cancel(cachedRun, button, running));
        } else {
            TransitionButton.State running = button.addState("Sync", syncIcon, "Reloads this report from external file", !readyToCancel, () -> sync(cachedRun, button));
            button.addState("CancelSync", killIcon, "Cancel this sync reload", readyToCancel, () -> cancelSync(cachedRun, button, running));
        }
        row.add(button);

        if (cachedRun.getExecutionRecord().isRunnable()) {
            row.add(createDeleteButton(cachedRun));
        }

        setRunStateListener(cachedRun, button);
    }

    private @NotNull JButton createDeleteButton(CachedRun cachedRun) {
        JButton button = new JButton(deleteIcon);
        button.setToolTipText("Delete this report");
        Project project = cachedRun.getProject();
        button.addActionListener(e -> {
            ApplicationManager.getApplication().invokeLater(() -> {
                if (MessageDialogBuilder.okCancel("Really delete this report?", "Cannot be undone")
                        .yesText("Confirm")
                        .noText("Cancel")
                        .ask(project)) {
                    if (cachedRun.isCurrent()) {
                        reloadScoresMsg(project, "Select a different report to the left.");
                    }
                    cachedRun.deleteFilesForThisRun();
                    reloadHistory(project);
                }
            });
        });
        button.setOpaque(false); // Don't fill the button background
        button.setContentAreaFilled(false); // Transparent content area
        button.setBorderPainted(false); // Optionally remove border
        button.setPreferredSize(TransitionButton.BUTTON_SIZE);
        button.setMinimumSize(TransitionButton.BUTTON_SIZE);
        button.setMaximumSize(TransitionButton.BUTTON_SIZE);
        return button;
    }

    private void setRunStateListener(CachedRun cachedRun, TransitionButton button) {
        cachedRun.setRunStateChangedListener((oldState, newState) ->
        {
            final boolean newRowState;
            final Boolean newClearAllState;
            if (oldState == RunState.RUNNING) {  // A run has ended
                System.out.println("Handle runState changed from RUNNING to " + newState);
                newRowState = true;
                if (activeRuns.decrementAndGet() == 0) {
                    AtomicBoolean anyGenerated = new AtomicBoolean(false);
                    PitRepo.apply(cachedRun.getProject(), (c, current) -> {
                        if (c.getExecutionRecord().isRunnable()) {
                            anyGenerated.set(true);
                        }
                    });
                    newClearAllState = anyGenerated.get();
                } else {
                    newClearAllState = null;
                }
            } else if (newState == RunState.RUNNING) {  // A run has started
                System.out.println("Handle runState changed from " + oldState + " to RUNNING");
                newRowState = false;
                newClearAllState = activeRuns.incrementAndGet() == 1;
            } else {
                System.out.println("Nuthin");
                return;
            }
            ApplicationManager.getApplication().invokeLater(() -> {
                button.setEnabled(newRowState);
                if (newClearAllState != null) {
                    clearAllButton.setEnabled(newClearAllState);
                }
            });
        });

    }

    /*
    private boolean run(CachedRun cachedRun, TransitionButton button) {
        Module module = cachedRun.ensureLoaded().getModule();
        ExecutionRecord record = cachedRun.getExecutionRecord();
        List<VirtualFile> vfs = record.getInputFiles().stream().map(file ->
                LocalFileSystem.getInstance().findFileByPath(file)).toList();
        ApplicationManager.getApplication().invokeLater(() -> {
            ApplicationManager.getApplication().executeOnPooledThread(() -> {
                ExecutionUtils.execute(module, vfs);
            });
        });
        return true;
    }
     */

    private boolean run(CachedRun cachedRun, TransitionButton button) {
        ExecutionUtils.dumpThreads("MutationControlPanel.run START");
        try {
            Module module = cachedRun.ensureLoaded().getModule();
            ExecutionRecord record = cachedRun.getExecutionRecord();
            List<VirtualFile> vfs = record.getInputFiles().stream()
                    .map(LocalFileSystem.getInstance()::findFileByPath)
                    .toList();
            ExecutionUtils.dumpThreads("MutationControlPanel.run OUTER");
            ApplicationManager.getApplication().executeOnPooledThread(() -> {
                ExecutionUtils.dumpThreads("MutationControlPanel.run INNER");
                ExecutionUtils.execute(module, vfs);
            });
            return true;
        } catch (Exception e) {
            LOGGER.error("Execution failed: " + e.getMessage(), e);
            return false;
        }
    }

    public void handleCompletion(CachedRun cachedRun) {
        reloadHistory(cachedRun.getProject());
    }

    private boolean cancel(CachedRun cachedRun, TransitionButton button, TransitionButton.State state) {
        if (cachedRun.cancel()) {
            reloadScores(cachedRun);
            return true;
        }
        return false;
    }

    private boolean sync(CachedRun cachedRun, TransitionButton button) {
        boolean result = true;
        try {
            cachedRun.reload();
        } catch (InvalidVirtualFileAccessException e) {
            cachedRun.setRunState(RunState.FAILED);
            markScoresInvalid();
            result = false;
        }
        reloadReports(cachedRun.getProject());
        return result;
    }

    private boolean cancelSync(CachedRun cachedRun, TransitionButton button, TransitionButton.State state) {
        cachedRun.setRunState(RunState.CANCELLED);  // TODO this enough?
        reloadReports(cachedRun.getProject());
        return true;
    }

    public void markScoresInvalid() {
        tree.resetToRootMessage("Select a run from the history list to the left.");
    }

    public boolean isGutterIconsEnabled() {
        return isGutterIconsEnabled;
    }

    public static class Level {
        private final ClickTree.TreeLevel treeLevel;

        Level(ClickTree.TreeLevel treeLevel) {
            this.treeLevel = treeLevel;
        }

        public void setLine(Project project, VirtualFile file, String fileName, IMutationScore score) {
            treeLevel.addClickableFileRow(project, file, createLine(fileName, score.getScore()));
        }

        public Level setLine(Project project, String pkgName, IMutationScore score) {
            return new Level(treeLevel.addPackageRow(createLine(pkgName, score.getScore())));

        }
    }

    private static String createLine(String text, float score) {
        String space = score == 100 ? "" : score > 10 ? "&nbsp;" : "&nbsp;&nbsp;";
        return String.format("<html>%d%%%s&nbsp;%s</html>", (int) score, space, text);
    }
}


